fullstack-development/developers-roadmap

- frontend/junior-1/js.md
Close #28 Поправил вопрос про массивы на первом джуне
> fix create array question in jun1

- frontend/junior-1/html.md
#49 Добавил источник альтернативы БЭМу
> add alternative bem source

- frontend/junior-2/git.md
#54 Добавил вопрос git vs github
> jun2: GIT, add git vs github question

- frontend/junior-3/ts.md
Удалил вопрос про exchaustiveness checking, он есть во 2м джуне
> jun3/ts: remove duplicate question

- frontend/junior-1/html.md
Считаю, что даже те базовые вещи, о которых говорит Макеев, у нас не делаются и на них забивается, с моей стороны в том числе, надеюсь что это было из-за незнания и теперь все станет лучше и не только у меня :)
В видосе говорится как надо делать, типа просто бери и используй
> jun1/html: add resource about semantic markup

- backend/junior-1/haskell.md
- backend/junior-1/linux.md
Отформатировала, чтобы удобнее было читать, как в карте фронтенда.
К сожалению, теперь не видно в диффе, какие вопросы добавились. 
Добавленные вопросы лучше смотреть в диффе на комит: https://github.com/fullstack-development/developers-roadmap/commit/74681dea0b6c40d3ad2fe142a2533306fdf92f6a
> Extend backend junior 1

- frontend/middle-3/fp.md
на собесе обговорим этот момент
> Mid3/fp: change questions order in Algebraic Data Types section

- frontend/middle-1/oop.md
> mid1/oop: add solid podcast resource

- backend/junior-1/haskell.md
https://github.com/fullstack-development/developers-roadmap/issues/146
> jun1/haskell: add additonal questions

- frontend/junior-3/git.md
Глянул по диагонали содержимое, все вещи показались полезными и изложено достаточно лаконично. По идее, должно быть полезно при подготовке и изучении
> jun3/git: update git resources

- backend/junior-1/haskell.md
- backend/junior-1/linux.md
- backend/middle-1/README.md
https://github.com/fullstack-development/developers-roadmap/issues/167
https://github.com/fullstack-development/developers-roadmap/issues/165
> Backend/Jun1/ 167, T165 remove and refactor themes

- frontend/middle-1/generators.md
Ссылки на learn.js отредачил (по старым если перейти, они как раз ссылаются на новые, обновленные, которые я сейчас написал)
Ссылку на симпсона сделал сразу на английскую книгу, потому что не понятно почему была ссылка на русскую книгу, но глава при этом была на английском
> middle1/generators: update recources

- backend/junior-2/haskell.md
https://github.com/fullstack-development/developers-roadmap/issues/174
Добавил простые вопросы про то как создать, убить и засинхронить треды на хаскеле вместе с источниками.
> [Backend]Add async topic for junior-2

- frontend/middle-1/design.md
https://github.com/fullstack-development/developers-roadmap/issues/183
- Српосить явно про горизонтальное и вертикальное Separation of Conserns
- Можно ли достичь вертикального CoS, но без горизонтального?
- Выпилить вопрос про полиморфизм в KISS
- блок Separation of concerns сразу добавить под Cohesion
- Добавить в Separation of concerns вопрос про сходство и различие с SRP и Cohesion
> middle1/desigh: refactoring

- frontend/middle-1/generators.md
Сейчас собесили Ваню Черкасова. Набросали изменения с @chmnkh и опять же Ваней, и я решил запечатлеть их в МР
> middle 1 - update generators

- backend/junior-1/haskell.md
https://github.com/fullstack-development/developers-roadmap/issues/201
> Jun-1/Haskell: Removed the duplicate question.

- shared/junior-1/git.md
> Replace git jun1 broken link

- backend/junior-2/haskell.md
Ссылка на доку по циклическим зависимостям модулей
> Ссылка на доку по циклическим зависимостям модулей

- frontend/middle-1/testing.md
> middle1/testing: fix Robert Marting typo

- frontend/middle-1/design.md
Наткнулся на неплохую статью, где описано, почему всё не так просто :)
> Add DRY resource

- frontend/junior-3/ts.md
- Немного уменьшил скомканность кода
- Поправил код в соответствии eslint airbnb
- Исправил пару ошибок
> Jun 3/ts: Refactor examples

- frontend/junior-3/ts.md
Подача информации в предложенном ресурсе как по мне лучше чем в доках typescript, дополнительно можно найти ответы на некоторые из вопросов по теме **const assertion**.
> Jun 3/ts: Add link to recursive type aliases

- frontend/junior-3/dom.md
Я вероятно не один такой, кто не встречал ранее свойство **innerText** и использовал **textContent** для аналогичных целей, но как выяснилось у этих свойств есть довольно серьезные различия о которых полезно знать.
> Jun-3/DOM: Mention textContent property

- backend/junior-1/haskell.md
Added questions about immutable data
Based on this https://github.com/fullstack-development/developers-roadmap/issues/212
> Immutable data - Junior1

- frontend/junior-1/css.md
В предыдущей статье предлагается тонзиллэктомия ректальным способом, метафорично выражаясь.
> Update CSS Jun1

- backend/junior-2/linux.md
"and principles" phrase has been removed, since it was a bit confusing. The
essence of the question is to list some IPC methods and describe them.
> jun2/linux: reword the IPC question and add links for it

- frontend/junior-3/react.md
1. удалил упоминание редакса, неактуалочка
2. удалил задачу в синтетик ивентах, потому что она сильно зависит от имплементации реакта: не понятно, например, когда отработает componentDidMount и когда реакт зарегает клик по кнопке в доме, что до, что после, от этого не понятно, какой хэндлер вообще первый сработает. В последнем реакте, вдобавок, событие не на документе, а на руте, но это сути не меняет.
3. вопрос про "альтернативу хокам" из пальца высосан, не понятно, что там надо, и какую пользу это принесет
> jun3/react: remove weird questions; remove redux;

- frontend/junior-2/ts.md
- frontend/middle-1/typescript.md
Branding и Flavoring:
1) достаточно нетривиальные и редкие приемы для уровня 2 джуна
2) достаточно редкие для того, чтобы быть раскрытыми таким большим количеством вопросов, имхо достаточно оставить общий вопрос, чтобы люди просто имели представление, что такие приемы есть, и могли освежить в памяти нюансы при необходимости
итого: перенос на миддла 1 в более короткой формек
> jun2/ts: move branding & flavoring to middle1

- backend/junior-2/linux.md
Ссылки перенесены в правильный раздел. Добавлены ссылки к некоторым вопросам, которые вызывали затруднения. Некоторые вопросы уточнил и сделал более требовательными, это на ваше усмотрение. Правки лучше смотреть по коммитам.
Усложнил вопрос про IPC: указал конкретные методы IPC, которые нужно освоить. Если первоначальная цель вопроса была в освоении того, что такое в принципе IPC, то для этого, мне кажется, нужно спрашивать конкретные, хорошо известные методы IPC. Без конкретики это очень расплывчатый вопрос, и оценивать его знание трудно. Приведенные методы несложные, концептуальные и не требуют хорошего знания UNIX/C. Сложные только сокеты, но представление о сокетах тоже желательно иметь.
Добавил вопрос про rwx-права доступа к каталогам. С каталогами не все просто.
> jun2/linux: clarify questions, add links

- backend/junior-1/haskell.md
Предложенные правки обсуждались в #265.
> jun1/haskell: clarify some questions (#265)

- backend/junior-2/linux.md
Обсуждалось в #285.
@olgaklimenko нужно твое ревью как автора идеи части вопросов. Мнение остальных тоже не помешало бы.
> jun2/linux: add questions about environment vars, man, and .profile

- backend/junior-3/haskell.md
- backend/middle-1/haskell.md
https://github.com/fullstack-development/developers-roadmap/issues/291
- Перенёс вопрос "Что такое кайнд" в DataKinds.
- Разместил источники по экстеншенам.
- Добавил несколько источников, которые обговорили в ишью.
- Переформулировал вопрос в DataKinds по функции из поднятого типа в неподнятое значение.
- Добавил DerivingVia.
- Перенёс вопрос по дженерик программирование и ConstraintKinds на мидла.
- Убрал курс по логике из источников Existential types. Он классный, но всё-таки не совсем относится.
> jun3-extensions-corrections

- frontend/middle-1/async.md
Video with Russian dubbing was removed
> Update async.md: remove link to removed video

- frontend/junior-3/ts.md
> jun3/ts: fixed spelling mistakes

- backend/junior-3/haskell.md
- backend/middle-1/haskell.md
See https://github.com/fullstack-development/developers-roadmap/issues/287#issuecomment-795168621
> jun3/haskell: move unliftio & monad-control questions to middle-1

- backend/junior-2/haskell.md
- backend/junior-3/haskell.md
- backend/middle-1/haskell.md
Задача: https://github.com/fullstack-development/developers-roadmap/issues/287
Решили не создавать 4го джуна, а перенести немного на 2го джуна и немного на миддла.
**На 2го джуна:**
- Deriving, RecordWildCards extensions
- Validation Applicative
- Monad (вопросы про runIO и трансформер IO) + дополнить вопросами про ST Monad (это в отдельной таске)
**на 1го миддла:**
- PolyKinds
- ConstraintKinds
- GHCi Debugger
+ в этом ПР поправила разметку Jun2, сделала её такой же,  как в Jun3 и Mid1.
> Упрощение jun3 Haskell

- backend/junior-3/Practice/DataKinds.hs
- backend/junior-3/Practice/ExistentialQuantification.hs
- backend/junior-3/Practice/FunctionalDependencies.hs
- backend/junior-3/README.md
- backend/junior-3/haskell.md
> Backend/jun 3/Extensions practice

- backend/junior-3/haskell.md
> jun 3 haskell type family section typo fix

- backend/middle-1/db.md
Добавил вопросы по нормализации БД, и по использованию транзакций в PostgreSQL.
Кроме того, добавил несколько статей из официальной документации PostgreSQL в источники.
> Back-end/Middle-1/Database: add questions about normal forms and PSQL transactions

- backend/middle-1/haskell.md
Добавил немного вопросов о вариантности функторов, обсуждали это на собеседовании. Вопросы не очень практичные, но несложные, полезные для понимания, и ответ есть в источниках.
> middle-1/haskell Add more questions about functor variance

- backend/middle-1/db.md
Удалил источники про нормализацию БД из-за найденных там неточностей (см. #338), добавил ссылки на английскую вики, чей материал мне нравится гораздо больше. Он сложнее, но если в нем разобраться, знания будут более фундаментальные, а не интуитивные. Мы  примерно то же изучали на 3 курсе универа, так что уровень материала посильный.
Добавил ссылку на книжку по БД. Ее можно найти на торрентах в русском переводе, там эта тема объяснена намного подробнее и с массой примеров. Не так, как на вики, но автор делает нужные оговорки, так что у него все корректно.
К сожалению. не нашел аналогичной замены старым источникам, с примерами нормализуемых таблиц. Перерыл где-то с десяток ссылок, включая ссылки с вики, - везде путают первичные и потенциальные ключи, а местами несут вообще полную отсебятину …
> Improve DB normalization links and add questions

- backend/middle-1/haskell.md
Вопрос про `ConstraintKinds` в генериках переформулировал в более общий - какие вообще бывают способы обобщённого программирования (помимо генериков), и какие расширения помогают в их использовании.
Кроме того, добавил два вопроса про `Generic1` и вопрос про ограничения (бывают ли типы, с которыми генерики не работают, и что с ними можно сделать).
> Вопросы Middle-1 Haskell Generics

- shared/middle/sicp.md
Поправил некоторые вопросы в generic operations, по которым нашлись проблемы при чтении.
Прошу обсудить еще вопросы:
Некоторые вопросы поправил так, что вы можете не согласиться, пройдитесь пожалуйста по моим замечаниям.
> SICP: fixing questions in generic operations

- backend/junior-1/haskell.md
Вопрос подробно обсуждается на первом мидле во время изучения книги СИКП. Для первого джуна понятия незначительные и могут больше запутать, чем помочь.
> jun1-haskell: removing iterative-recursive algorithms difference question

- backend/README.md
- backend/optional/docker.md
Топик по докеру. Цель - покрыть базовые понятия и механизмы, чтобы после сдачи человек мог уверенно себя чуствовать на проектах и писать\разбираться в файлах докера. Задачу сделать топик для докер-сеньора не ставил, если появится углубленная версия, то пометим эту как первую часть, но там уже, наверное, и в Kubernetes можно будет заходить. Будет круто, если кто-то накидает источников, потому что всё что мне требуется я выдёргиваю из официальной доки\гугла маленькими кусками.
> backend: added docker topic

- backend/README.md
- backend/optional/metrics.md
Топик по метрикам после которого разработчик должен уметь оперировать понятиями, встречающимися при настройке метрик, уметь пользоваться Prometheus и Grafana, настраивать их и экспортировать кастомные метрики из своего приложения.
Мне не довелось долго работать с этими инструментами, поэтому если я упустил какие-то важные вещи, то, пожалуйста, дополните :)
> backend: added metrics topic

- backend/README.md
- backend/optional/ssh-protocol.md
Сделал тут небольшой топик по ssh, который может быть когда-нибудь может стать частью полноценного топика по девопсу.
> added ssh topic

- frontend/middle-1/fp.md
> Add one question to mid1 FP

- frontend/junior-3/api.md
Туториал - https://www.restapitutorial.com/
Cтатья на Хабре - https://habr.com/ru/companies/oleg-bunin/articles/433322/
> Добавил 2 ссылки для Rest API.

- shared/junior-3/git.md
- shared/junior-3/testing.md
shared/junior3/git:
- Подвинул вопрос про HEAD под вопрос про The Three Trees
shared/junior3/testing:
- убрал битую ссылку
- добавил ресурсы с ответами на вопросы
> Поправил пару тем в shared/jun3
